version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: delivery-food-db
    environment:
      POSTGRES_DB: fooddb
      POSTGRES_USER: fooduser
      POSTGRES_PASSWORD: foodpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - delivery-network

volumes:
  postgres_data:

networks:
  delivery-network:
    driver: bridge 